services:
  data:
    image: mariadb
    container_name: data
    environment:
      MARIADB_RANDOM_ROOT_PASSWORD: "1"
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    networks:
      - tp3

  script:
    build: ./php
    container_name: script
    volumes:
      - ./src:/app
    depends_on:
      - data
    networks:
      - tp3

  http:
    image: nginx
    container_name: http
    ports:
      - "8080:80"
    volumes:
      - ./src:/app
      - ./config/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - script
    networks:
      - tp3

networks:
  tp3: {}
